#!/bin/bash

set -euo pipefail

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)

usage() {
	cat <<EOF
Usage: $0 <freerdp-source-dir> [build-dir]

Configure and build the shared FreeRDP client libraries required by the
macrdp loopback client. The source directory should be the pinned FreeRDP
source generated by the main macrdp CMake build.

Environment:
  MACRDP_FREERDP_CLIENT_JOBS       Parallel build jobs (default: host CPUs)
  MACRDP_FREERDP_CLIENT_GENERATOR  CMake generator (default: Unix Makefiles)
  MACRDP_FREERDP_CLIENT_ARCH       CMake architecture (default: host arch)
  MACRDP_FREERDP_CLIENT_DEPLOYMENT_TARGET
                                   macOS target (default: 15.0)
  MACRDP_FREERDP_CLIENT_PREFIX     CMake prefix path override
EOF
}

if [ "$#" -eq 1 ]; then
	case "$1" in
		-h|--help)
			usage
			exit 0
			;;
	esac
fi

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
	usage >&2
	exit 2
fi

freerdp_source=$1
build_dir=${2:-$repo_dir/build-freerdp-client}
generator=${MACRDP_FREERDP_CLIENT_GENERATOR:-Unix Makefiles}
architecture=${MACRDP_FREERDP_CLIENT_ARCH:-$(uname -m)}
deployment_target=${MACRDP_FREERDP_CLIENT_DEPLOYMENT_TARGET:-15.0}
jobs=${MACRDP_FREERDP_CLIENT_JOBS:-}
prefix_path=${MACRDP_FREERDP_CLIENT_PREFIX:-}

if [ ! -f "$freerdp_source/CMakeLists.txt" ] \
	|| [ ! -f "$freerdp_source/include/freerdp/client.h" ]; then
	echo "FreeRDP source directory is missing the expected files: $freerdp_source" >&2
	exit 2
fi

if [ -z "$jobs" ]; then
	jobs=$(sysctl -n hw.ncpu 2>/dev/null || printf '4')
fi
case "$jobs" in
	''|*[!0-9]*)
		echo "MACRDP_FREERDP_CLIENT_JOBS must be a positive integer" >&2
		exit 2
		;;
esac
if [ "$jobs" -lt 1 ]; then
	echo "MACRDP_FREERDP_CLIENT_JOBS must be a positive integer" >&2
	exit 2
fi

cmake_args=(
	-S "$freerdp_source"
	-B "$build_dir"
	-G "$generator"
	-DCMAKE_BUILD_TYPE=Release
	-DCMAKE_OSX_ARCHITECTURES="$architecture"
	-DCMAKE_OSX_DEPLOYMENT_TARGET="$deployment_target"
	-DBUILD_SHARED_LIBS=ON
	-DWITH_CLIENT=ON
	-DWITH_CLIENT_COMMON=ON
	-DWITH_CLIENT_CHANNELS=ON
	-DWITH_SERVER=OFF
	-DWITH_SERVER_INTERFACE=OFF
	-DWITH_SHADOW=OFF
	-DWITH_PROXY=OFF
	-DWITH_SAMPLE=OFF
	-DWITH_MANPAGES=OFF
	-DWITH_DOCUMENTATION=OFF
	-DWITH_CLANG_FORMAT=OFF
	-DWITH_INSTALL_CLIENT_DESKTOP_FILES=OFF
	-DWITH_FFMPEG=ON
	-DWITH_VIDEO_FFMPEG=ON
	-DWITH_SWSCALE=ON
	-DWITH_DSP_FFMPEG=ON
	-DWITH_OPENSSL=ON
	-DWITH_OPENH264=OFF
	-DWITH_OPUS=OFF
	-DWITH_VIDEOTOOLBOX=OFF
	-DWITH_VAAPI_H264_ENCODING=OFF
	-DWITH_PCSC=OFF
	-DWITH_SMARTCARD_EMULATE=OFF
	-DWITH_SMARTCARD_INSPECT=OFF
	-DWITH_CUPS=OFF
	-DWITH_MACAUDIO=OFF
	-DWITH_CLIENT_MAC=OFF
	-DWITH_CLIENT_SDL=OFF
	-DWITH_CLIENT_SDL2=OFF
	-DWITH_CLIENT_SDL3=OFF
	-DWITH_X11=OFF
	-DWITH_WAYLAND=OFF
	-DWITH_XCURSOR=OFF
	-DWITH_XEXT=OFF
	-DWITH_XFIXES=OFF
	-DWITH_XI=OFF
	-DWITH_XINERAMA=OFF
	-DWITH_XRANDR=OFF
	-DWITH_XRENDER=OFF
	-DWITH_XV=OFF
	-DWITH_WINPR_TOOLS=OFF
	-DWITH_WINPR_TOOLS_CLI=OFF
	-DWITH_WIN_CONSOLE=OFF
	-DCMAKE_C_FLAGS=-I${repo_dir}/include
	-DCHANNEL_AINPUT=OFF
	-DCHANNEL_AUDIN=OFF
	-DCHANNEL_DISP=OFF
	-DCHANNEL_DRIVE=OFF
	-DCHANNEL_ECHO=OFF
	-DCHANNEL_GEOMETRY=OFF
	-DCHANNEL_LOCATION=OFF
	-DCHANNEL_PARALLEL=OFF
	-DCHANNEL_PRINTER=OFF
	-DCHANNEL_RAIL=OFF
	-DCHANNEL_RDPEAR=OFF
	-DCHANNEL_RDPECAM=OFF
	-DCHANNEL_RDPEI=OFF
	-DCHANNEL_RDPEMSC=OFF
	-DCHANNEL_RDPEWA=OFF
	-DCHANNEL_SERIAL=OFF
	-DCHANNEL_SMARTCARD=OFF
	-DCHANNEL_SSHAGENT=OFF
	-DCHANNEL_TELEMETRY=OFF
	-DCHANNEL_TSMF=OFF
	-DCHANNEL_URBDRC=OFF
	-DCHANNEL_VIDEO=OFF
	-DCHANNEL_CLIPRDR_CLIENT=ON
	-DCHANNEL_DRDYNVC_CLIENT=ON
	-DCHANNEL_ENCOMSP_CLIENT=ON
	-DCHANNEL_RDPDR_CLIENT=ON
	-DCHANNEL_RDPGFX_CLIENT=ON
	-DCHANNEL_RDPSND_CLIENT=ON
	-DCHANNEL_REMDESK_CLIENT=ON
)
if [ -n "$prefix_path" ]; then
	cmake_args+=("-DCMAKE_PREFIX_PATH=$prefix_path")
fi

cmake "${cmake_args[@]}"

cmake --build "$build_dir" --parallel "$jobs"

echo "FreeRDP loopback client build ready: $build_dir"
