#pragma once

#include <filesystem>

namespace macrdp {

// Restrict only the directories and files generated by macrdp/FreeRDP.
// Unrelated entries below the configured root are intentionally untouched.
bool restrict_config_paths(const std::filesystem::path& root);

} // namespace macrdp
